# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - pip install -U coverage
  - pip install -U coveralls
  - pip install -U codecov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Command to run tests, e.g. python setup.py test
script:
  - tox
  - coverage run --source asamplelib -m pytest
  - coverage report -m

after_script:
  - coveralls
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    python: 3.8
{%- endif %}
